version: '28.8.1'
services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: meuapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: